[package]
name = "twitter-user-tracker"
version = "0.1.1"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]

[dependencies]
base64 = "0.4"
env_logger = "0.4"
hyper = "0.10"
hyper-rustls = "0.3"
log = "0.3"
postgres = "0.14"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
